# Cross-compilation image: assumes the morph-reth binary has already been
# compiled for $TARGETPLATFORM and placed in ./dist/bin/$TARGETARCH/
FROM --platform=$TARGETPLATFORM ubuntu:22.04

LABEL org.opencontainers.image.source=https://github.com/morph-l2/morph-reth
LABEL org.opencontainers.image.licenses="MIT OR Apache-2.0"

# Filled by docker buildx
ARG TARGETARCH

COPY ./dist/bin/$TARGETARCH/morph-reth /usr/local/bin/morph-reth

EXPOSE 8545 8546 8551 30303 30303/udp
ENTRYPOINT ["/usr/local/bin/morph-reth"]
