global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: morph-reth
    metrics_path: "/"
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9001']
        labels:
          service: sequencer0-reth
          role: sequencer
          chain: morph-devnet
      - targets: ['host.docker.internal:9002']
        labels:
          service: full0-reth
          role: full
          chain: morph-devnet
      - targets: ['host.docker.internal:9003']
        labels:
          service: full1-reth
          role: full
          chain: morph-devnet
