[profile.default]
slow-timeout = { period = "30s", terminate-after = 4 }

[profile.ci]
test-threads = "num-cpus"
retries = { backoff = "exponential", count = 2, delay = "2s", jitter = true }
fail-fast = false
slow-timeout = { period = "30s", terminate-after = 4 }
