name: Test Cross Build (temporary)

on:
  push:
    branches: ["fix/cross-build-release"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Cross Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: cross-test-${{ matrix.target }}

      - name: Install cross main
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build binary
        run: cross build --release --locked --target ${{ matrix.target }} --bin morph-reth
